-- ============================================================
-- V2: Creación de tablas GRUPOS, PRIVILEGIOS y tablas de relación
-- Compatible con Oracle 10g
-- ============================================================

-- Secuencia para grupos
CREATE SEQUENCE SEQ_GRUPOS
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Secuencia para privilegios
CREATE SEQUENCE SEQ_PRIVILEGIOS
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Tabla de grupos
CREATE TABLE GRUPOS (
    ID          NUMBER(19)    NOT NULL,
    NOMBRE      VARCHAR2(100) NOT NULL,
    DESCRIPCION VARCHAR2(500),
    ESTADO      VARCHAR2(20)  NOT NULL,
    CONSTRAINT PK_GRUPOS PRIMARY KEY (ID),
    CONSTRAINT UK_GRUPOS_NOMBRE UNIQUE (NOMBRE),
    CONSTRAINT CK_GRUPOS_ESTADO CHECK (ESTADO IN ('ACTIVO','INACTIVO','SUSPENDIDO','BLOQUEADO'))
);

CREATE OR REPLACE TRIGGER TRG_GRUPOS_ID
    BEFORE INSERT ON GRUPOS
    FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        SELECT SEQ_GRUPOS.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
END;
/

-- Tabla de privilegios
CREATE TABLE PRIVILEGIOS (
    ID          NUMBER(19)    NOT NULL,
    CODIGO      VARCHAR2(50)  NOT NULL,
    NOMBRE      VARCHAR2(100) NOT NULL,
    DESCRIPCION VARCHAR2(500),
    ACCION      VARCHAR2(100) NOT NULL,
    RECURSO     VARCHAR2(200) NOT NULL,
    CONSTRAINT PK_PRIVILEGIOS PRIMARY KEY (ID),
    CONSTRAINT UK_PRIVILEGIOS_CODIGO UNIQUE (CODIGO)
);

CREATE OR REPLACE TRIGGER TRG_PRIVILEGIOS_ID
    BEFORE INSERT ON PRIVILEGIOS
    FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        SELECT SEQ_PRIVILEGIOS.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
END;
/

-- Relación Usuario - Grupo (N:M)
CREATE TABLE USUARIO_GRUPO (
    USUARIO_ID  NUMBER(19) NOT NULL,
    GRUPO_ID    NUMBER(19) NOT NULL,
    CONSTRAINT PK_USUARIO_GRUPO PRIMARY KEY (USUARIO_ID, GRUPO_ID),
    CONSTRAINT FK_UG_USUARIO FOREIGN KEY (USUARIO_ID) REFERENCES USUARIOS(ID),
    CONSTRAINT FK_UG_GRUPO   FOREIGN KEY (GRUPO_ID)   REFERENCES GRUPOS(ID)
);

-- Relación Grupo - Privilegio (N:M)
CREATE TABLE GRUPO_PRIVILEGIO (
    GRUPO_ID      NUMBER(19) NOT NULL,
    PRIVILEGIO_ID NUMBER(19) NOT NULL,
    CONSTRAINT PK_GRUPO_PRIVILEGIO PRIMARY KEY (GRUPO_ID, PRIVILEGIO_ID),
    CONSTRAINT FK_GP_GRUPO      FOREIGN KEY (GRUPO_ID)      REFERENCES GRUPOS(ID),
    CONSTRAINT FK_GP_PRIVILEGIO FOREIGN KEY (PRIVILEGIO_ID) REFERENCES PRIVILEGIOS(ID)
);

-- Datos iniciales de privilegios
INSERT INTO PRIVILEGIOS (CODIGO, NOMBRE, DESCRIPCION, ACCION, RECURSO)
    VALUES ('USR_CREAR', 'Crear Usuario', 'Permite crear nuevos usuarios', 'POST', '/api/v1/usuarios');
INSERT INTO PRIVILEGIOS (CODIGO, NOMBRE, DESCRIPCION, ACCION, RECURSO)
    VALUES ('USR_LEER', 'Leer Usuarios', 'Permite consultar usuarios', 'GET', '/api/v1/usuarios');
INSERT INTO PRIVILEGIOS (CODIGO, NOMBRE, DESCRIPCION, ACCION, RECURSO)
    VALUES ('USR_EDITAR', 'Editar Usuario', 'Permite editar usuarios', 'PUT', '/api/v1/usuarios');
INSERT INTO PRIVILEGIOS (CODIGO, NOMBRE, DESCRIPCION, ACCION, RECURSO)
    VALUES ('USR_ELIMINAR', 'Eliminar Usuario', 'Permite eliminar usuarios', 'DELETE', '/api/v1/usuarios');
INSERT INTO PRIVILEGIOS (CODIGO, NOMBRE, DESCRIPCION, ACCION, RECURSO)
    VALUES ('GRP_ADMIN', 'Administrar Grupos', 'Permite gestionar grupos', 'ALL', '/api/v1/grupos');

-- Grupo administrador por defecto
INSERT INTO GRUPOS (NOMBRE, DESCRIPCION, ESTADO) VALUES ('ADMINISTRADOR', 'Grupo con acceso total al sistema', 'ACTIVO');
INSERT INTO GRUPOS (NOMBRE, DESCRIPCION, ESTADO) VALUES ('CONSULTOR', 'Grupo con acceso de solo lectura', 'ACTIVO');

COMMIT;
